programa ::= <instruccion> | <programa> <instruccion>

instruccion ::= <declaracion> :_:
                | <asignacion> :_:
                | <instruccion_salida> :_:
                | <instruccion_entrada> :_:
                
declaracion ::= <tipo_dato> <lista_declaraciones>

tipo_dato ::= entero | decimal | caracter | cadena | booleano

lista_declaraciones ::= <declaracion_simple> | <lista_declaraciones>, <declaracion_simple>

declaracion_simple> ::= IDENTIFICADOR = <expresion> | IDENTIFICADOR

asignacion ::= IDENTIFICADOR = <expresion>

instruccion_salida ::= mt < <lista_elementos_salida> >

lista_elementos_salida ::= <elemento_salida> | <lista_elementos_salida>, <elemento_salida>

elemento_salida ::= < <expresion> 

instruccion_entrada> ::= inp < IDENTIFICADOR >

expresion> ::= <termino> | <termino> + <termino> | <termino> - <termino>

termino> ::= <factor> | <factor> * <factor> | <factor> / <factor>

factor ::= NUMERO
           | IDENTIFICADOR
           | <expresion> 
           | <cadena_literal>
           | <caracter>
           | <booleano>
cadena_literal::= @CARACTERES@ | @ CARACTERES @

booleano ::= true | false

caracter ::= 'CARACTER'